INSERT INTO dbo.Brands ([Brand Name],[Manufacturer Name]) VALUES 
('Hills Science Diet','Hills Pet Nutrition'),
('Hills™ Prescription Diet','Hills Pet Nutrition'),
('Purina Veterinary Diets','Purina'),
('PURINA ONE® SMARTBLEND®','Purina'),
('PURINA ONE SMARTBLEND','Purina'),
('PURINA PROPLAN(SAVOR®)','Purina'),
('PURINA PROPLAN(SPORT®)','Purina'),
('PURINA PROPLAN(FOCUS)','Purina'),
('PURINA PROPLAN(SELECT®)','Purina'),
('PURINA PROPLAN(SELECT™)','Purina'),
('PURINA Beneful®','Purina'),
('Purina® Dog Chow®','Purina'),
('Purina Beyond®','Purina'),
('Natures Variety® Instinct® Raw','Natures Variety'),
('Natures Variety® Instinct®','Natures Variety'),
('Natures Variety® Instinct® Raw Boost','Natures Variety'),
('Natures Variety® Instinct® Healthy Weight','Natures Variety'),
('Natures Variety® Instinct® Limited','Natures Variety'),
('Natures Variety® Prairie®','Natures Variety'),
('Iams® ProActive Health™','Iams'),
('Iams® Grain Free Naturals™','Iams'),
('Iams® Healthy Naturals™','Iams'),
('Iams® Sensitive Naturals™','Iams'),
('Iams® Premium Protection™','Iams'),
('Iams® Veterinary Formula™','Iams'),
('Iams® So Good™','Iams'),
('Iams® Woof Delights','Iams'),
('Iams® Shakeables','Iams'),
('Royal Canin BREED HEALTH NUTRITION™','Royal Canin'),
('Royal Canin','Royal Canin'),
('Royal CaninX-SMALL','Royal Canin'),
('Royal Canin X-SMALL','Royal Canin'),
('Royal CaninMINI','Royal Canin'),
('Royal CaninMEDIUM','Royal Canin'),
('Royal CaninMAXI','Royal Canin'),
('Royal CaninGIANT','Royal Canin'),
('Royal CaninCanine Health Nutrition Wet','Royal Canin'),
('Diamond Naturals', 'Diamond'),
('Diamond','Diamond'),
('Diamond Naturals Grain-Free','Diamond'),
('Solid Gold','Solid Gold'),
('Blue Buffalo Life Protection Formula®','Blue Buffalo'),
('Blue Buffalo BLUE Freedom®','Blue Buffalo'),
('Blue Buffalo BLUE Basics®','Blue Buffalo'),
('BLUE Wilderness®','Blue Buffalo'),
('BLUE Homestyle Recipe®','Blue Buffalo'),
('BLUE Freedom®','Blue Buffalo'),
('BLUE Bones®','Blue Buffalo'),
('BLUE Mini Bars®','Blue Buffalo'),
('BLUE Bits®','Blue Buffalo'),
('BLUE Wilderness® Wild Chews','Blue Buffalo'),
('Life Protection Formula®','Blue Buffalo'),
('BLUE Basics®','Blue Buffalo'),
('BLUE Healthy Starts™','Blue Buffalo'),
('BLUE Chunky Stew™','Blue Buffalo'),
('BLUE Divine Delights™','Blue Buffalo'),
('BLUE Freedom® Grain-Free Grillers','Blue Buffalo'),
('BLUE Wilderness® Wild Cuts Trail Toppers™','Blue Buffalo'),
('BLUE Wilderness® Rocky Mountain Recipe™','Blue Buffalo'),
('BLUE Wilderness® Wolf Creek Stew™','Blue Buffalo'),
('Blues Stew®','Blue Buffalo'),
('Boo Stew','Blue Buffalo'),
('BLUE Family Favorite Recipes®','Blue Buffalo'),
('BLUE Kitchen Cravings™','Blue Buffalo'),
('BLUE Boo Bars™','Blue Buffalo'),
('BLUE Wilderness® Dental Chews','Blue Buffalo'),
('BLUE Wilderness Trail Treats®','Blue Buffalo'),
('BLUE™ Health Bars','Blue Buffalo'),
('BLUE Bites®','Blue Buffalo'),
('BLUE Super Bars™','Blue Buffalo'),
('BLUE Stix™','Blue Buffalo'),
('BLUE Mini Stix™','Blue Buffalo'),
('BLUE Exuberance!®','Blue Buffalo'),
('BLUE Tranquility®','Blue Buffalo'),
('BLUE Wilderness Trail Treats ®','Blue Buffalo'),
('BLUE Joint Sticks™','Blue Buffalo'),
('BLUE Jolly Joints®','Blue Buffalo');